[server]
enableStaticServing = true

[theme]
primaryColor = "#2483E2"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#37352f"
linkColor = "#73716E"
borderColor = "#D9D9D9"
showWidgetBorder = true
baseRadius = "0.4rem"
font = 'ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI Variable Display", "Segoe UI", Helvetica, "Apple Color Emoji", Arial, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol"'
codeFont = "SF Mono"
codeBackgroundColor = "#F7F6F3"
codeFontSize = "13.6px"
headingFontSizes = ["40px", "30px", "24px", "20px"]
headingFontWeights = ["700", "600", "600", "600"]
chartCategoricalColors = [
    "#2d99eb",
    "#e7b533",
    "#62bd8f",
    "#a57ad9",
    "#ea8b43",
    "#de66a6",
    "#02b5d0",
    "#e05f58",
]
chartSequentialColors = [
    "#e1f0fc",
    "#d2e8fa",
    "#c3e1f9",
    "#add3f6",
    "#9accf5",
    "#85c0f3",
    "#70b7f1",
    "#50a8ec",
    "#2d99eb",
    "#198ee9",
]

blueTextColor = "#2483e2"
greenTextColor = "#55a77c"
yellowTextColor = "#e5b245"
orangeTextColor = "#d5803b"
redTextColor = "#e56458"
violetTextColor = "#b577d7"
grayTextColor = "#8f8b87"

blueBackgroundColor = "#e8f2fa"
greenBackgroundColor = "#e8f1ec"
yellowBackgroundColor = "#f9f3dc"
orangeBackgroundColor = "#fcebde"
redBackgroundColor = "#fce9e7"
violetBackgroundColor = "#f4ebf9"
grayBackgroundColor = "#f0efed"


[theme.sidebar]
backgroundColor = "#f8f8f7"

[[theme.fontFaces]]
url = "app/static/sf-mono/SFMonoRegular.otf"
family = "SF Mono"
