[server]
enableStaticServing = true

[theme]
primaryColor = "#1A6CE7"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#fbfbfb"
textColor = "#1E252F"
linkColor = "#1a6ce7"
borderColor = "#D6DAE5"
showWidgetBorder = true
font = "Inter:https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
codeFont = "Apercu Mono Pro:https://fonts.cdnfonts.com/css/apercu-mono-pro"
baseFontSize = 14
baseRadius = "6px"
codeBackgroundColor = "#f7f7f7"
codeFontSize = "14px"
headingFontSizes = ["28px", "20px", "16px", "14px", "14px"]
headingFontWeights = [700, 700, 600, 600, 400]
chartCategoricalColors = [
    "#1a6ce7",
    "#b2cdf7",
    "#edb701",
    "#ffe692",
    "#52caa6",
    "#89dbc2",
    "#d3122f",
    "#f9bcc5",
    "#7257f4",
    "#cfc5fb",
    "#ff7d1e",
    "#ffbe8f",
    "#70deff",
    "#beefff",
    "#d45cff",
    "#edb9ff",
]
chartSequentialColors = [
    "#f1f7ff",
    "#d6e6ff",
    "#bbd6fe",
    "#86b6fc",
    "#5999f8",
    "#3581f2",
    "#1a6ce7",
    "#085bd7",
    "#004cbe",
    "#003e9a",
]

blueColor = "#1a6de7"
greenColor = "#0e9c73"
orangeColor = "#ff7d1e"
redColor = "#d31430"
violetColor = "#7157f5"
yellowColor = "#f3be11"
grayColor = "#bec4d6"

blueBackgroundColor = "#d6e7ff"
greenBackgroundColor = "#bdf9ea"
# orangeBackgroundColor = ""
redBackgroundColor = "#ffd1dc"
violetBackgroundColor = "#ded8fd"
yellowBackgroundColor = "#ffedce"
grayBackgroundColor = "#edeef1"

blueTextColor = "#002c6e"
greenTextColor = "#034238"
# orangeTextColor = ""
redTextColor = "#66000d"
violetTextColor = "#402d9f"
yellowTextColor = "#663e03"
grayTextColor = "#1d252f"


[theme.sidebar]
backgroundColor = "#F7F7F7"
secondaryBackgroundColor = "#fbfbfb"

[[theme.fontFaces]]
url = "app/static/Inter-VariableFont_opsz,wght.ttf"
family = "Inter"

[[theme.fontFaces]]
url = "app/static/ApercuMonoProRegular.ttf"
family = "Apercu Mono Pro"
